version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3.9.4-management
    mem_limit: 350m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  consumer1:
    build: consumer
    mem_limit: 350m
    depends_on:
      rabbitmq:
        condition: service_healthy

  producer:
    build: producer
    mem_limit: 350m
    ports:
      - 8001:8001
    depends_on:
      rabbitmq:
        condition: service_healthy