
spring:
#H2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace # 파라미터를 같이 보여줌

