


spring:
#  mysql
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/spring-batch
#      username: root
#      password: root
  h2:
    console:
      enabled: true
      path: h2
  datasource:
    hikari:
      #jdbc-url: jdbc:h2:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
