server:
  port: 8002
  address: 0.0.0.0

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

mq:
  exchange-name: mart.topic
  queue-name: cashier.queue
  queue-name1: tasting.queue
  routing-key: buy.stuff.#
  routing-key1: eat.stuff.#