server.port: 8004
server.error.include-message: always

#spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: queue.log.messages # exchange
#          binder: local_rabbit
#        output:
#          destination: queue.pretty.log.messages #exchange
#          binder: local_rabbit
#        myOutput:
#          destination: queue.my.log.messages #exchange
#          binder: local_rabbit
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 127.0.0.1
#                port: 5672
#                username: guest
#                password: guest
#                virtual-host: /


spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: stream-exchange
    group: stream-comsumer-queue
  bindings.new-input:
    destination: stream-exchange-other
    group: stream-consumer-other-queue



#spring.cloud.stream.bindings.input.consumer:
#  maxAttempts: 3
#  backOffInitialInterval: 500
#  backOffMaxInterval: 1000
#  backOffMultiplier: 2.0

#spring.cloud.stream.rabbit.bindings.input.consumer:
#  autoBindDlq: true
#  republishToDlq: true

spring.cloud.stream.rabbit.bindings.input.consumer:
  bindingRoutingKey: #, hello.#, power.#, big.#
  bindingRoutingKeyDelimiter: ','


spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

