server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: mfa
    jpa:
        show-sql: true
        generate-ddl: false
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    datasource: 
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3308/security?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root
    thymeleaf:
        cache: false
        encoding: UTF-8
        prefix: classpath:/templates/
        mode: HTML
        suffix: .html

logging:
    level:
        root: INFO
        com.yg.practice.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type: trace
        org.hibernate.type.descriptor.sql: trace