server:
  port: 8080
  servlet:
    context-path: /

spring:
  h2:
    console:
      enabled: true
      path: /h2
  #  datasource:
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/security?characterEncoding=UTF-8&serverTimezone=UTC
  #    username: root
  #    password: root
  datasource:
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:~/test
  application:
    name: mfa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html

logging:
  level:
    root: INFO
    org.yg.practice.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: DEBUG