spring:
  config:
    activate:
      on-profile: sql
  datasource:
    url: jdbc:mysql://localhost:23306/test_jpa?characterEncoding=UTF-8&rewriteBatchedStatements=true&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: DEBUG
    org.springframework.transaction: ERROR
    org.springframework.orm.jpa: ERROR

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
