
spring:
  profiles:
    active: local
  datasource:
    hikari:
      connection-timeout: 10000
      max-lifetime: 300000
      maximum-pool-size: 30
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true


  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 100
#        order_inserts: true
#        order_updates: true
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
        #generate_statistics: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace
#    org.springframework.transaction: DEBUG
#    org.springframework.orm.jpa: DEBUG
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace # 파라미터를 같이 보여줌

