spring:
  config:
    activate:
      on-profile: sql
  datasource:
    url: jdbc:p6spy:mysql://localhost:23306/test_jpa?characterEncoding=UTF-8&rewriteBatchedStatements=true&jdbcCompliantTruncation=false
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update