spring:
  datasource:
    url: jdbc:p6spy:h2:~/test-db
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false

