
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/springbatch
    username: root
    password: root
  batch:
    initialize-schema: always
    job:
      names: ${job.name:createArticleJob} #JOB Name이 넘어오면 Job을 실행하고 그렇지 않으면 실행 하지 않음
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
